### ISSUE TITLE
process of creating environment was stuck

### ISSUE THREAD

**Issue by Alirgnahs** [crimBubble/ECCsplorer#7]
conda env create -f environment.yml
This cmd ran for a whole night and the environment hasn't been solved.
<img width="327" alt="Snipaste_2022-01-18_08-39-25" src="https://user-images.githubusercontent.com/97293873/149851664-3556e45a-1b1f-4f1c-8c3c-04c955ccb9ee.png">

**Comment by crimBubble** [comment]
This is a normal behavior of conda solving more complex environments. It is not stuck but depending on your machine this may take some time. It ensures that the pipeline will run as intended.

**Comment by nemitheasura** [comment]
Dear @crimBubble, @Alirgnahs,

I had the same issue. In my case, conda was solving environment for 16 hours (sic!), before I interrupted. I understand that sometimes environment solving takes some time, but not that much.

I ran conda env create with -vv option to see where the problem was. It turns out that conda was stuck at SAT solver  (ran into an endless loops). 

I debugged it by changing the order of the channels in your *.yml file, so I set the defaults at the highest priority, then conda-forge, bioconda etc. I also specified the python version (3.7.10), so it did not have to iterate across all of the repos. 

I also set channel priority to strict and wiped pickles from the previous, unsuccessfull attempts. This allowed me to complete the installation in 20 minutes. 

I post it so you may consider editing your config. 

Have a nice day,
Nemi

**Comment by crimBubble** [comment]
Dear @nemitheasura,
thanks a lot for your comment. I was not aware that the channel order has this much influence on resolving the environment. I will test your suggestions and update the .yml file soon.
